version: "3.8"

services:
  rag-app:
    build: .
    container_name: finance-rag-fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload